---
enable_ufw_firewall: true
reboot_box: false

install_packages:
  - autossh
  - curl
  - nfs-common
  - nmap
  - python-dev
  - python3-pip
  - python3-virtualenv
  - screen

pyhton_packages:
  - build-essential
  - checkinstall
  - libreadline-gplv2-dev
  - libncursesw5-dev
  - libssl-dev
  - libsqlite3-dev
  - tk-dev
  - libgdbm-dev
  - libc6-dev
  - libbz2-dev
  - libffi-dev
  - zlib1g-dev

masscan_install_packages:
  - git
  - gcc
  - libpcap-dev
  - make

# Python virtual environment.
engine_dir: /root/engine
venv_dir: "{{ engine_dir }}/.venv"
venv_python: "{{ venv_dir }}/bin/python3"

# Additional nmap .nse script file URLs.  Will be saved in /usr/share/nmap/scripts/
nse_script_urls:
  - https://raw.githubusercontent.com/theMiddleBlue/nmap-elasticsearch-nse/master/elasticsearch.nse
