---
- hosts: console
  environment:
    http_proxy: http://10.28.73.1:8090
    https_proxy: http://10.28.73.1:8090
  roles:
    - name: common
      tags: [ common ]
    - name: add_users
      tags: [ add_users ]
    - name: console
      tags: [ console ]
